print('Hello, world!')
print('what is your name?')
my_name = input('>')
print('It is good to mee you, ' + my_name)
print('The length of your name is:')
print(len(my_name))
print('What is your age?')
my_age = input('>')
print('you will be ' + str(int(my_age)+ 1) + ' in a year.')
